// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Tesseract from 'tesseract.js';
import { createWorker } from 'tesseract.js';
import { Buffer } from 'buffer';

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {"TesseractOCR.Enum_Languages.afr"|"TesseractOCR.Enum_Languages.amh"|"TesseractOCR.Enum_Languages.ara"|"TesseractOCR.Enum_Languages.asm"|"TesseractOCR.Enum_Languages.aze"|"TesseractOCR.Enum_Languages.aze_cyrl"|"TesseractOCR.Enum_Languages.bel"|"TesseractOCR.Enum_Languages.ben"|"TesseractOCR.Enum_Languages.bod"|"TesseractOCR.Enum_Languages.bos"|"TesseractOCR.Enum_Languages.bul"|"TesseractOCR.Enum_Languages.cat"|"TesseractOCR.Enum_Languages.ceb"|"TesseractOCR.Enum_Languages.ces"|"TesseractOCR.Enum_Languages.chi_sim"|"TesseractOCR.Enum_Languages.chi_tra"|"TesseractOCR.Enum_Languages.chr"|"TesseractOCR.Enum_Languages.cym"|"TesseractOCR.Enum_Languages.dan"|"TesseractOCR.Enum_Languages.deu"|"TesseractOCR.Enum_Languages.dzo"|"TesseractOCR.Enum_Languages.ell"|"TesseractOCR.Enum_Languages.eng"|"TesseractOCR.Enum_Languages.enm"|"TesseractOCR.Enum_Languages.epo"|"TesseractOCR.Enum_Languages.est"|"TesseractOCR.Enum_Languages.eus"|"TesseractOCR.Enum_Languages.fas"|"TesseractOCR.Enum_Languages.fin"|"TesseractOCR.Enum_Languages.fra"|"TesseractOCR.Enum_Languages.frk"|"TesseractOCR.Enum_Languages.frm"|"TesseractOCR.Enum_Languages.gle"|"TesseractOCR.Enum_Languages.glg"|"TesseractOCR.Enum_Languages.grc"|"TesseractOCR.Enum_Languages.guj"|"TesseractOCR.Enum_Languages.hat"|"TesseractOCR.Enum_Languages.heb"|"TesseractOCR.Enum_Languages.hin"|"TesseractOCR.Enum_Languages.hrv"|"TesseractOCR.Enum_Languages.hun"|"TesseractOCR.Enum_Languages.iku"|"TesseractOCR.Enum_Languages.ind"|"TesseractOCR.Enum_Languages.isl"|"TesseractOCR.Enum_Languages.ita"|"TesseractOCR.Enum_Languages.ita_old"|"TesseractOCR.Enum_Languages.jav"|"TesseractOCR.Enum_Languages.jpn"|"TesseractOCR.Enum_Languages.kan"|"TesseractOCR.Enum_Languages.kat"|"TesseractOCR.Enum_Languages.kat_old"|"TesseractOCR.Enum_Languages.kaz"|"TesseractOCR.Enum_Languages.khm"|"TesseractOCR.Enum_Languages.kir"|"TesseractOCR.Enum_Languages.kor"|"TesseractOCR.Enum_Languages.kur"|"TesseractOCR.Enum_Languages.lao"|"TesseractOCR.Enum_Languages.lat"|"TesseractOCR.Enum_Languages.lav"|"TesseractOCR.Enum_Languages.lit"|"TesseractOCR.Enum_Languages.mal"|"TesseractOCR.Enum_Languages.mar"|"TesseractOCR.Enum_Languages.mkd"|"TesseractOCR.Enum_Languages.mlt"|"TesseractOCR.Enum_Languages.msa"|"TesseractOCR.Enum_Languages.mya"|"TesseractOCR.Enum_Languages.nep"|"TesseractOCR.Enum_Languages.nld"|"TesseractOCR.Enum_Languages.nor"|"TesseractOCR.Enum_Languages.ori"|"TesseractOCR.Enum_Languages.pan"|"TesseractOCR.Enum_Languages.pol"|"TesseractOCR.Enum_Languages.por"|"TesseractOCR.Enum_Languages.pus"|"TesseractOCR.Enum_Languages.ron"|"TesseractOCR.Enum_Languages.rus"|"TesseractOCR.Enum_Languages.san"|"TesseractOCR.Enum_Languages.sin"|"TesseractOCR.Enum_Languages.slk"|"TesseractOCR.Enum_Languages.slv"|"TesseractOCR.Enum_Languages.spa"|"TesseractOCR.Enum_Languages.spa_old"|"TesseractOCR.Enum_Languages.sqi"|"TesseractOCR.Enum_Languages.srp"|"TesseractOCR.Enum_Languages.srp_latn"|"TesseractOCR.Enum_Languages.swa"|"TesseractOCR.Enum_Languages.swe"|"TesseractOCR.Enum_Languages.syr"|"TesseractOCR.Enum_Languages.tam"|"TesseractOCR.Enum_Languages.tel"|"TesseractOCR.Enum_Languages.tgk"|"TesseractOCR.Enum_Languages.tgl"|"TesseractOCR.Enum_Languages.tha"|"TesseractOCR.Enum_Languages.tir"|"TesseractOCR.Enum_Languages.tur"|"TesseractOCR.Enum_Languages.uig"|"TesseractOCR.Enum_Languages.ukr"|"TesseractOCR.Enum_Languages.urd"|"TesseractOCR.Enum_Languages.uzb"|"TesseractOCR.Enum_Languages.uzb_cyrl"|"TesseractOCR.Enum_Languages.vie"|"TesseractOCR.Enum_Languages.yid"} loadLanguage
 * @param {"TesseractOCR.Enum_Languages.afr"|"TesseractOCR.Enum_Languages.amh"|"TesseractOCR.Enum_Languages.ara"|"TesseractOCR.Enum_Languages.asm"|"TesseractOCR.Enum_Languages.aze"|"TesseractOCR.Enum_Languages.aze_cyrl"|"TesseractOCR.Enum_Languages.bel"|"TesseractOCR.Enum_Languages.ben"|"TesseractOCR.Enum_Languages.bod"|"TesseractOCR.Enum_Languages.bos"|"TesseractOCR.Enum_Languages.bul"|"TesseractOCR.Enum_Languages.cat"|"TesseractOCR.Enum_Languages.ceb"|"TesseractOCR.Enum_Languages.ces"|"TesseractOCR.Enum_Languages.chi_sim"|"TesseractOCR.Enum_Languages.chi_tra"|"TesseractOCR.Enum_Languages.chr"|"TesseractOCR.Enum_Languages.cym"|"TesseractOCR.Enum_Languages.dan"|"TesseractOCR.Enum_Languages.deu"|"TesseractOCR.Enum_Languages.dzo"|"TesseractOCR.Enum_Languages.ell"|"TesseractOCR.Enum_Languages.eng"|"TesseractOCR.Enum_Languages.enm"|"TesseractOCR.Enum_Languages.epo"|"TesseractOCR.Enum_Languages.est"|"TesseractOCR.Enum_Languages.eus"|"TesseractOCR.Enum_Languages.fas"|"TesseractOCR.Enum_Languages.fin"|"TesseractOCR.Enum_Languages.fra"|"TesseractOCR.Enum_Languages.frk"|"TesseractOCR.Enum_Languages.frm"|"TesseractOCR.Enum_Languages.gle"|"TesseractOCR.Enum_Languages.glg"|"TesseractOCR.Enum_Languages.grc"|"TesseractOCR.Enum_Languages.guj"|"TesseractOCR.Enum_Languages.hat"|"TesseractOCR.Enum_Languages.heb"|"TesseractOCR.Enum_Languages.hin"|"TesseractOCR.Enum_Languages.hrv"|"TesseractOCR.Enum_Languages.hun"|"TesseractOCR.Enum_Languages.iku"|"TesseractOCR.Enum_Languages.ind"|"TesseractOCR.Enum_Languages.isl"|"TesseractOCR.Enum_Languages.ita"|"TesseractOCR.Enum_Languages.ita_old"|"TesseractOCR.Enum_Languages.jav"|"TesseractOCR.Enum_Languages.jpn"|"TesseractOCR.Enum_Languages.kan"|"TesseractOCR.Enum_Languages.kat"|"TesseractOCR.Enum_Languages.kat_old"|"TesseractOCR.Enum_Languages.kaz"|"TesseractOCR.Enum_Languages.khm"|"TesseractOCR.Enum_Languages.kir"|"TesseractOCR.Enum_Languages.kor"|"TesseractOCR.Enum_Languages.kur"|"TesseractOCR.Enum_Languages.lao"|"TesseractOCR.Enum_Languages.lat"|"TesseractOCR.Enum_Languages.lav"|"TesseractOCR.Enum_Languages.lit"|"TesseractOCR.Enum_Languages.mal"|"TesseractOCR.Enum_Languages.mar"|"TesseractOCR.Enum_Languages.mkd"|"TesseractOCR.Enum_Languages.mlt"|"TesseractOCR.Enum_Languages.msa"|"TesseractOCR.Enum_Languages.mya"|"TesseractOCR.Enum_Languages.nep"|"TesseractOCR.Enum_Languages.nld"|"TesseractOCR.Enum_Languages.nor"|"TesseractOCR.Enum_Languages.ori"|"TesseractOCR.Enum_Languages.pan"|"TesseractOCR.Enum_Languages.pol"|"TesseractOCR.Enum_Languages.por"|"TesseractOCR.Enum_Languages.pus"|"TesseractOCR.Enum_Languages.ron"|"TesseractOCR.Enum_Languages.rus"|"TesseractOCR.Enum_Languages.san"|"TesseractOCR.Enum_Languages.sin"|"TesseractOCR.Enum_Languages.slk"|"TesseractOCR.Enum_Languages.slv"|"TesseractOCR.Enum_Languages.spa"|"TesseractOCR.Enum_Languages.spa_old"|"TesseractOCR.Enum_Languages.sqi"|"TesseractOCR.Enum_Languages.srp"|"TesseractOCR.Enum_Languages.srp_latn"|"TesseractOCR.Enum_Languages.swa"|"TesseractOCR.Enum_Languages.swe"|"TesseractOCR.Enum_Languages.syr"|"TesseractOCR.Enum_Languages.tam"|"TesseractOCR.Enum_Languages.tel"|"TesseractOCR.Enum_Languages.tgk"|"TesseractOCR.Enum_Languages.tgl"|"TesseractOCR.Enum_Languages.tha"|"TesseractOCR.Enum_Languages.tir"|"TesseractOCR.Enum_Languages.tur"|"TesseractOCR.Enum_Languages.uig"|"TesseractOCR.Enum_Languages.ukr"|"TesseractOCR.Enum_Languages.urd"|"TesseractOCR.Enum_Languages.uzb"|"TesseractOCR.Enum_Languages.uzb_cyrl"|"TesseractOCR.Enum_Languages.vie"|"TesseractOCR.Enum_Languages.yid"} initializeLanguage
 * @param {string} base64Image
 * @returns {Promise.<string>}
 */
export async function JS_TesseractOCR(loadLanguage, initializeLanguage, base64Image) {
	// BEGIN USER CODE
	const { createWorker } = require('tesseract.js');
	let imageBuffer = Buffer.from(base64Image, "base64");

const worker = createWorker({
  logger: m => console.log(m), // Add logger here
});


const result=(async () => {
  await worker.load();
  await worker.loadLanguage(loadLanguage);
  await worker.initialize(initializeLanguage);
  const { data: { text } } = await worker.recognize(imageBuffer);
  await worker.terminate();
  return text;
})();
  return result;
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
