// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tesseractocr.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TesseractOCR module
	public static tesseractocr.proxies.Image dS_CreateImage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("TesseractOCR.DS_CreateImage").withParams(params).execute(context);
		return result == null ? null : tesseractocr.proxies.Image.initialize(context, result);
	}
	public static java.lang.String sUB_GetBase64Image(IContext context, tesseractocr.proxies.Image _image)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Image", _image == null ? null : _image.getMendixObject());
		return (java.lang.String) Core.microflowCall("TesseractOCR.SUB_GetBase64Image").withParams(params).execute(context);
	}
}